# Generated by Django 5.2.8 on 2026-02-09 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_date"]},
        ),
    ]
